###
POST {{host}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL

query {
  auth (
    dto: {
      login: "{{login}}"
      password: "{{password}}"
    }
  ) {
    access_token
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}

###
POST {{host}}/graphql
Content-Type: application/json
X-REQUEST-TYPE: GraphQL
Authorization: Bearer {{token}}

query {
  getSessionInfo {
    access_token
    id
    code
    name_first
    name_last
    description
    mail
    role
  }
}