export enum ERRORS {
  BDD_SERVICE_SQL_NO_FILTER = 'BDD_SERVICE_SQL_NO_FILTER',
  GET_BANK_USECASE_WRONG_SECRET = 'GET_BANK_USECASE_WRONG_SECRET',
  GET_USER_USECASE_USER_NOT_FOUND = 'GET_USER_USECASE_USER_NOT_FOUND',
  GET_BANK_USECASE_BANK_NOT_FOUND = 'GET_BANK_USECASE_BANK_NOT_FOUND',
  GET_BANK_USECASE_USER_NOT_IN_MEMBERS = 'GET_BANK_USECASE_USER_NOT_IN_MEMBERS',
}
